name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Set Environment File
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test