name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel_devops
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_mysql

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist
      
    - name: Set up .env
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel_devops" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=User@1234" >> .env

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test
